In [6]:
import pandas as pd
import numpy as np

In [3]:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:

a = np.array([1,2,3])

In [9]:
type(a)

numpy.ndarray

In [10]:
type(data)

list

In [11]:
type(series)

pandas.core.series.Series

In [14]:
data1 = {
    'Name': ['Andy','Honey','Chitti'],
    'Age': [25,27,65],
    'Location': ['Canada', 'UK', 'France']
}

In [15]:
type(data1)

dict

In [16]:
df = pd.DataFrame(data1)
print(df)
print(type(df))

     Name  Age Location
0    Andy   25   Canada
1   Honey   27       UK
2  Chitti   65   France
<class 'pandas.core.frame.DataFrame'>

In [29]:
np.array(df)

array([['Andy', 25, 'Canada'],
       ['Honey', 27, 'UK'],
       ['Chitti', 65, 'France']], dtype=object)

In [27]:
type(arr)

numpy.ndarray

In [30]:
df.isnull()

    Name    Age  Location
0  False  False     False
1  False  False     False
2  False  False     False

In [34]:
df.isnull().any(axis=1)

0    False
1    False
2    False
dtype: bool

In [35]:
df[df.isnull()]

  Name  Age Location
0  NaN  NaN      NaN
1  NaN  NaN      NaN
2  NaN  NaN      NaN

In [38]:
df1 = pd.read_csv(r'C:\Users\sures\DSI\dsi_python\python\05_src\data\assignment_2_data\inflammation_01.csv')

df1.head(5)

,0,0.1,1,3,1.1,2,4,7,8,3.1,...,4.3,4.4,5.1,7.6,3.4,4.5,2.1,3.5,0.2,0.3
0,0,1,2,1,2,1,3,2,2,6,...,3,5,4,4,5,5,1,1,0,1
1,0,1,1,3,3,2,6,2,5,9,...,10,5,4,2,2,3,2,2,1,1
2,0,0,2,0,4,2,2,1,6,7,...,3,5,6,3,3,4,2,3,2,1
3,0,1,1,3,3,1,3,5,2,4,...,9,6,3,2,2,4,2,0,1,1
4,0,0,1,2,2,4,2,1,6,4,...,8,4,7,3,5,4,4,3,2,1

In [40]:
df1.mean(axis=1)

0     5.425
1     6.100
2     5.900
3     5.550
4     6.225
5     5.975
6     6.650
7     6.625
8     6.525
9     6.775
10    5.800
11    6.225
12    5.750
13    5.225
14    6.300
15    6.550
16    5.700
17    5.850
18    6.550
19    5.775
20    5.825
21    6.175
22    6.100
23    5.800
24    6.425
25    6.050
26    6.025
27    6.175
28    6.550
29    6.175
30    6.350
31    6.725
32    6.125
33    7.075
34    5.725
35    5.925
36    6.150
37    6.075
38    5.750
39    5.975
40    5.725
41    6.300
42    5.900
43    6.750
44    5.925
45    7.225
46    6.150
47    5.950
48    6.275
49    5.700
50    6.100
51    6.825
52    5.975
53    6.725
54    5.700
55    6.250
56    6.400
57    7.050
58    5.900
dtype: float64

In [41]:
df1.describe()

,0,0.1,1,3,1.1,2,4,7,8,3.1,...,4.3,4.4,5.1,7.6,3.4,4.5,2.1,3.5,0.2,0.3
count,59.0,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,...,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000
mean,0.0,0.457627,1.118644,1.728814,2.457627,3.169492,3.796610,3.830508,5.186441,5.559322,...,6.101695,5.983051,5.118644,3.542373,3.305085,3.559322,2.491525,1.474576,1.152542,0.576271
std,0.0,0.502478,0.744746,1.063996,1.134446,1.391508,1.739794,1.940072,1.925103,2.276349,...,2.544059,2.129364,1.651381,1.755013,1.793227,1.405300,1.135218,1.164947,0.805446,0.498390
min,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,0.0,0.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,4.000000,4.000000,...,4.000000,4.500000,4.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.500000,0.000000
50%,0.0,0.000000,1.000000,2.000000,2.000000,3.000000,4.000000,4.000000,5.000000,6.000000,...,6.000000,6.000000,5.000000,4.000000,3.000000,4.000000,2.000000,1.000000,1.000000,1.000000
75%,0.0,1.000000,2.000000,3.000000,3.000000,4.000000,5.000000,5.000000,6.500000,7.000000,...,8.000000,8.000000,6.000000,5.000000,5.000000,5.000000,4.000000,3.000000,2.000000,1.000000
max,0.0,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,9.000000,...,10.000000,9.000000,8.000000,7.000000,6.000000,5.000000,4.000000,3.000000,2.000000,1.000000